apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-k8s-app
  template:
    metadata:
      labels:
        app: flask-k8s-app
    spec:
      containers:
      - name: flask-k8s-app
        image: flask-k8s-app:latest  # Use the updated image name
        imagePullPolicy: Never  # Prevent Kubernetes from trying to pull the image
        ports:
          - containerPort: 5000
        env:
          - name: DB_HOST
            value: "postgres"   

          - name: DB_USER
            value: "test"

          - name: DB_PASS
            value: "test"

          - name: DB_NAME
            value: "arafat_database"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
spec:
  selector:
    app: flask-k8s-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
