apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
spec:
  selector:
    app: flask-k8s-app
  ports:
    - protocol: TCP
      port: 5000        # The port that the service will expose internally
      targetPort: 5000  # The port on the container that the service will forward traffic to
      nodePort: 30001   # The port exposed on the node (can be any port within the range 30000-32767)
  type: NodePort       # Exposes the service externally using a NodePort
