apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  releaseName: postgresql
  interval: 5m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "12.6.6" # Use latest minor version
  values:
    auth:
      postgresPassword: test
    primary:
      persistence:
        enabled: false
